#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  This is a personal portfolio logging all my products and passions to date. This page is built upon a Jekyll GitHub Pages base and tied to a Google Domain.

contact: >
  # Contact

  You may contact me [through my email](mailto:gavin.kiener@case.edu). Let me know if you have any questions about my projects, or anything else!

#-------------------------------
# Work Section

projects:
- {name: 'Jetson Face Mask Detection', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Southpaw Custom Keyboard', folder: 'proj-2', file: 'projects/proj-2.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/gavin-kiener-6b6a48189/'}
- {icon: 'envelope', link: 'mailto:gavin.kiener@case.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
